<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("NOT_SHOW_NAV_CHAIN", "Y");
$APPLICATION->SetTitle("О компании");
?><?$user = array(
'1' => 'LAST_NAME, NAME,  SECOND_NAME',
'2' => 'PERSONAL_MOBILE',
'3' => 'EMAIL',
);?> <?$APPLICATION->IncludeComponent("ip:mailform_4.8", "ajax", array(
	"MAIL_RECIPIENT" => "service@nmir.ru",
	"SUBJECT" => "Отзыв с сайта",
	"BCC" => "info@nmir.ru, nmir-service@yandex.ru, inet@nmir.ru",
	"NAME_MAIL_RECIPIENT" => "Cайт Новый мир",
	"FROM" => "info@nmir.ru",
	"TYPE" => "Отзыв",
	"FORM_ID" => "feedback",
	"COUNT" => "4",
	"PLACEHOLDERS" => "Y",
	"BUTTON" => "Отправить",
	"TEXT" => "",
	"FORM_TITLE" => "Оставить отзыв",
	"MANAGER_BACK" => "N",
	"USER_CONNECTION" => json_encode($user),
	"F1_NAME" => "Ваше имя",
	"F1_PLACEHOLDER" => "Иванов Иван Иванович",
	"F1_TYPE" => "text",
	"F1_OBLIG" => "Y",
	"F1_TYPE" => "text",
	"F1_OBLIG" => "Y",
	"F2_NAME" => "Телефон",
	"F2_PLACEHOLDER" => "+7 (XXX) XXX-XX-XX",
	"F2_TYPE" => "phone",
	"F2_OBLIG" => "N",
	"F3_NAME" => "E-mail",
	"F3_PLACEHOLDER" => "you@email.ru",
	"F3_TYPE" => "mail",
	"F3_OBLIG" => "Y",
	"F4_NAME" => "Комментарий",
	"F4_PLACEHOLDER" => "Ваши пожелания",
	"F4_TYPE" => "textarea",
	"F4_OBLIG" => "N",
	"SHOW_LOG" => "Y",
	"MAGAZINE_CONNECT" => "N",
	"LOG_FORMAT" => "ib",
	"LOG_TYPE" => "user_messages",
	"LOG_ID" => "5",
	"MOD_LOG" => "Y",
	"F1_CONNECT" => "fio",
	"F2_CONNECT" => "tel",
	"F3_CONNECT" => "mail",
	"F4_CONNECT" => "PREVIEW_TEXT",
	"USER_CONNECT" => "user"
	),
	false
);?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>